#!/usr/bin/env python3
"""Extract Linux's usb_kbd_keycode[256] into a C header for the HID test.

DERIVED, NOT TRANSCRIBED.  The table is read out of
vendor/linux-<ver>/drivers/hid/usbhid/usbkbd.c -- the same GPL-2.0 file the
kernel compiles -- because a hand copy is a copy that drifts, and this one is
being used as an ORACLE.  usbkbd.c cannot be compiled standalone (it is a live
USB driver needing a HID core, an input device and a URB), so the array is
lifted rather than linked.

What it is an oracle FOR is narrow and worth stating: Linux maps a HID usage to
a KEYCODE, not to a character, so it cannot say what ASCII a key produces.  It
can say which usages are keys at all, and which distinct usages are the SAME
key -- 0x31 and 0x32 both map to keycode 43.  Those are the two relations
tests/drivers/usb/test_usb_hid.c checks the Fortran table against.

Usage:  tools/gen-hid-oracle.py <usbkbd.c> <out.h>
"""
import re
import sys

def main(src, dst):
    text = open(src, encoding="utf-8", errors="replace").read()
    m = re.search(r"usb_kbd_keycode\[256\]\s*=\s*\{(.*?)\}\s*;", text, re.S)
    if not m:
        sys.exit(f"{src}: no usb_kbd_keycode[256] initialiser found")
    body = re.sub(r"/\*.*?\*/", " ", m.group(1), flags=re.S)
    vals = [int(v) for v in re.findall(r"-?\d+", body)]
    # The initialiser is SHORT of 256 on purpose -- it stops at the last
    # non-zero entry and C zero-fills the rest.  Padding here rather than
    # demanding 256 keeps the extraction honest about what the file says.
    if not 128 <= len(vals) <= 256:
        sys.exit(f"{src}: usb_kbd_keycode has {len(vals)} entries, "
                 "which is not a plausible 256-entry initialiser")
    vals += [0] * (256 - len(vals))
    rows = [", ".join(f"{v:3d}" for v in vals[i:i + 16]) for i in range(0, 256, 16)]
    with open(dst, "w") as f:
        f.write("/* SPDX-License-Identifier: GPL-2.0 */\n")
        f.write(f"/* GENERATED by tools/gen-hid-oracle.py from {src}. */\n")
        f.write("static const unsigned char usb_kbd_keycode[256] = {\n")
        for r in rows:
            f.write(f"\t{r},\n")
        f.write("};\n")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
