#!/usr/bin/env python3
"""Generate the Fortran 8x16 bitmap font table from the kernel's own font source.

The 4096 glyph bytes are NOT invented and NOT hand-transcribed: they are read
out of vendor/linux-<ver>/lib/fonts/font_8x16.c, the same GPL-2.0 file the
kernel compiles into font_vga_8x16.  That gives the table a real differential
oracle (tests/drivers/video/test_gop_renderer.c compares all 4096 bytes against
the compiled C object) instead of a 4096-byte leap of faith.

Fortran has no unsigned types, so each byte is emitted PRE-BIASED into the
signed c_int8_t of identical bit pattern (0xFF -> -1).  vga_font_row() masks
the low 8 bits back out on the way to the caller.  See the module header.

Usage:  tools/gen-font-8x16.py <font_8x16.c> <target.f90>
Rewrites the region between the BEGIN/END GENERATED FONT DATA markers in
<target.f90> in place.  Re-running it on an unchanged input is a no-op, so
`git diff --exit-code` after a run proves the checked-in table is genuine.
"""
import re
import sys

GLYPHS, ROWS = 256, 16
TOTAL = GLYPHS * ROWS
BEGIN = "  ! BEGIN GENERATED FONT DATA"
END = "  ! END GENERATED FONT DATA"
PER_LINE = 8
BLOCK = 256  # bytes per parameter chunk -> 32 continuation lines, far under the
             # 255-continuation limit that one 4096-element constructor would blow.

# Matches only the glyph bytes.  The struct's `{ 0, 0, FONTDATAMAX, 0 }` header
# uses decimal/macro values on the declaration line, so it cannot be picked up.
BYTE_RE = re.compile(r"^\s*(0x[0-9a-fA-F]{2}),\s*(?:/\*.*\*/)?\s*$")


def extract(path):
    out = []
    with open(path) as fh:
        for line in fh:
            m = BYTE_RE.match(line)
            if m:
                out.append(int(m.group(1), 16))
    if len(out) != TOTAL:
        sys.exit(f"error: expected {TOTAL} font bytes in {path}, found {len(out)}")
    if any(b < 0 or b > 255 for b in out):
        sys.exit("error: a parsed value is not a byte")
    return out


def biased(b):
    """0x00..0xFF -> the c_int8_t holding the identical 8 bits."""
    return b - 256 if b > 127 else b


def emit(data, src):
    L = [
        BEGIN,
        "  ! Generated by tools/gen-font-8x16.py -- DO NOT EDIT BY HAND.",
        f"  ! Source: {src}  (fontdata_8x16, {TOTAL} bytes, GPL-2.0)",
        "  ! Regenerate with:  python3 tools/gen-font-8x16.py \\",
        f"  !     {src} \\",
        "  !     src/drivers/video/fk_gop_renderer.f90",
        "  ! Bytes are pre-biased into signed c_int8_t of identical bit pattern",
        f"  ! (0xFF -> -1).  Split into {TOTAL // BLOCK} chunks of {BLOCK} so no single array",
        "  ! constructor approaches the 255-continuation-line limit.",
    ]
    nblocks = TOTAL // BLOCK
    for blk in range(nblocks):
        chunk = data[blk * BLOCK:(blk + 1) * BLOCK]
        first, last = blk * BLOCK // ROWS, ((blk + 1) * BLOCK // ROWS) - 1
        L.append(f"  ! glyphs {first}..{last}  (0x{first:02X}..0x{last:02X})")
        L.append(f"  integer(c_int8_t), parameter :: FONT_BLK{blk:02d}(0:{BLOCK - 1}) = &")
        L.append("      [integer(c_int8_t) :: &")
        for i in range(0, BLOCK, PER_LINE):
            vals = ", ".join(f"{biased(b):4d}" for b in chunk[i:i + PER_LINE])
            tail = " ]" if i + PER_LINE >= BLOCK else ", &"
            L.append(f"      {vals}{tail}")
    L.append("  ! The flat table actually indexed at run time: FONT_8X16(ch*16 + row).")
    L.append(f"  integer(c_int8_t), parameter :: FONT_8X16(0:{TOTAL - 1}) = &")
    L.append("      [ &")
    for blk in range(0, nblocks, 4):
        names = ", ".join(f"FONT_BLK{b:02d}" for b in range(blk, min(blk + 4, nblocks)))
        tail = " ]" if blk + 4 >= nblocks else ", &"
        L.append(f"      {names}{tail}")
    L.append(END)
    return L


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    csrc, target = sys.argv[1], sys.argv[2]
    body = emit(extract(csrc), csrc)

    with open(target) as fh:
        lines = fh.read().splitlines()
    try:
        b = next(i for i, s in enumerate(lines) if s.startswith(BEGIN))
        e = next(i for i, s in enumerate(lines) if s.startswith(END))
    except StopIteration:
        sys.exit(f"error: {target} has no BEGIN/END GENERATED FONT DATA markers")

    new = lines[:b] + body + lines[e + 1:]
    # compliance.sh rejects free-form source with exactly 5 leading spaces.
    for i, s in enumerate(new):
        if re.match(r"^     [^ ]", s):
            sys.exit(f"error: generated line {i + 1} has 5 leading spaces (fixed-form trap)")
    with open(target, "w") as fh:
        fh.write("\n".join(new) + "\n")
    print(f"wrote {TOTAL} font bytes into {target}")


if __name__ == "__main__":
    main()
