#!/usr/bin/env python3
"""Generate the Fortran 8x16 bitmap font table from the kernel's own font source.

The 4096 glyph bytes are NOT invented and NOT hand-transcribed: they are read
out of vendor/linux-<ver>/lib/fonts/font_8x16.c, the same GPL-2.0 file the
kernel compiles into font_vga_8x16.  That gives the table a real differential
oracle (tests/drivers/video/test_gop_renderer.c compares all 4096 bytes against
the compiled C object) instead of a 4096-byte leap of faith.

Fortran has no unsigned types, so each byte is emitted PRE-BIASED into the
signed c_int8_t of identical bit pattern (0xFF -> -1).  vga_font_row() masks
the low 8 bits back out on the way to the caller.  See the module header.

Usage:  tools/gen-font-8x16.py <font_8x16.c> <target.f90>
        (the target today is src/drivers/video/fk_font_8x16.f90)
Rewrites the region between the BEGIN/END GENERATED FONT DATA markers in
<target.f90> in place.  Re-running it on an unchanged input is a no-op, so
`git diff --exit-code` after a run proves the checked-in table is genuine.
"""
import re
import sys

GLYPHS, ROWS = 256, 16
TOTAL = GLYPHS * ROWS
BEGIN = "  ! BEGIN GENERATED FONT DATA"
END = "  ! END GENERATED FONT DATA"
# 20 values per line is the tuned point between two hard compiler limits:
#   * 4096/20 = 205 continuation lines, under the 255-continuation maximum;
#   * 6 indent + 20*4 digits + 19*2 separators + " &" = 126 columns, under the
#     132-column free-form line limit.
# Emitting the table as SIXTEEN chunk parameters concatenated into a seventeenth
# stayed inside both limits too, but gfortran then emits all seventeen arrays
# into .rodata -- 8192 bytes of kernel image for 4096 bytes of font. One
# constructor costs one symbol.
PER_LINE = 20

# Matches only the glyph bytes.  The struct's `{ 0, 0, FONTDATAMAX, 0 }` header
# uses decimal/macro values on the declaration line, so it cannot be picked up.
BYTE_RE = re.compile(r"^\s*(0x[0-9a-fA-F]{2}),\s*(?:/\*.*\*/)?\s*$")


def extract(path):
    out = []
    with open(path) as fh:
        for line in fh:
            m = BYTE_RE.match(line)
            if m:
                out.append(int(m.group(1), 16))
    if len(out) != TOTAL:
        sys.exit(f"error: expected {TOTAL} font bytes in {path}, found {len(out)}")
    if any(b < 0 or b > 255 for b in out):
        sys.exit("error: a parsed value is not a byte")
    return out


def biased(b):
    """0x00..0xFF -> the c_int8_t holding the identical 8 bits."""
    return b - 256 if b > 127 else b


def emit(data, src, dst):
    L = [
        BEGIN,
        "  ! Generated by tools/gen-font-8x16.py -- DO NOT EDIT BY HAND.",
        f"  ! Source: {src}  (fontdata_8x16, {TOTAL} bytes, GPL-2.0)",
        "  ! Regenerate with:  python3 tools/gen-font-8x16.py \\",
        f"  !     {src} \\",
        f"  !     {dst}",
        "  ! Bytes are pre-biased into signed c_int8_t of identical bit pattern",
        "  ! (0xFF -> -1).  One single constructor, not concatenated chunks:",
        "  ! chunk parameters would each get their own .rodata symbol and double",
        f"  ! the table to {TOTAL * 2} bytes of kernel image.",
    ]
    L.append(f"  integer(c_int8_t), parameter :: FONT_8X16(0:{TOTAL - 1}) = &")
    L.append("      [integer(c_int8_t) :: &")
    for i in range(0, TOTAL, PER_LINE):
        vals = ", ".join(f"{biased(b):4d}" for b in data[i:i + PER_LINE])
        tail = " ]" if i + PER_LINE >= TOTAL else ", &"
        L.append(f"      {vals}{tail}")
    L.append(END)
    return L


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    csrc, target = sys.argv[1], sys.argv[2]
    body = emit(extract(csrc), csrc, target)

    with open(target) as fh:
        lines = fh.read().splitlines()
    try:
        b = next(i for i, s in enumerate(lines) if s.startswith(BEGIN))
        e = next(i for i, s in enumerate(lines) if s.startswith(END))
    except StopIteration:
        sys.exit(f"error: {target} has no BEGIN/END GENERATED FONT DATA markers")

    new = lines[:b] + body + lines[e + 1:]
    # compliance.sh rejects free-form source with exactly 5 leading spaces.
    for i, s in enumerate(new):
        if re.match(r"^     [^ ]", s):
            sys.exit(f"error: generated line {i + 1} has 5 leading spaces (fixed-form trap)")
        if len(s) > 132:
            sys.exit(f"error: generated line {i + 1} is {len(s)} columns (free-form limit is 132)")
    cont = sum(1 for s in body if s.rstrip().endswith("&"))
    if cont > 250:
        sys.exit(f"error: {cont} continuation lines, too close to the 255 maximum")
    with open(target, "w") as fh:
        fh.write("\n".join(new) + "\n")
    print(f"wrote {TOTAL} font bytes into {target}")


if __name__ == "__main__":
    main()
